default_install_hook_types: [
  commit-msg,
  pre-commit,
]
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]

  # TODO: add prettier

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
        args:
          - --config .markdownlint-cli2.yaml

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.14.0
    hooks:
        - id: commitlint
          stages: [ commit-msg ]
          additional_dependencies: [ '@commitlint/config-conventional' ]
